# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HoldedProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for HoldedProject
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end
